version: "3.7"
services:
    api:
        image: golang:1.16-stretch
        entrypoint: cicd/bin/entrypoint.sh
        ports:
            - 8000:8000
        volumes:
            - .:/app
        working_dir: /app
