service: lambda-mock-server

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
    name: aws
    runtime: go1.x
    stage: prod
    region: ap-southeast-2
    memorySize: 128
    timeout: 10
    iamManagedPolicies:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
    iamRoleStatements:
        -
            Effect: 'Allow'
            Action:
                - "dynamodb:PutItem"
                - "dynamodb:GetItem"
                - "dynamodb:UpdateItem"
                - "dynamodb:DeleteItem"
                - "dynamodb:Scan"
            Resource:
                - 'Fn::Join':
                    - ':'
                    -
                        - 'arn:aws:dynamodb'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'table/${self:custom.tableName}'

custom:
    tableName: lambda-mock-server-document

package:
    exclude:
        - ./**
    include:
        - ./bin/**

functions:
    api:
        handler: bin/main
        environment:
            GIN_MODE: release
        events:
            - http:
                path: /{any+}
                method: ANY

resources:
    Resources:
        DocumentTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    -
                        AttributeName: id
                        AttributeType: S
                KeySchema:
                    -
                        AttributeName: id
                        KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
