service: lambda-mock-server

frameworkVersion: ">=2.0.0"

provider:
    name: aws
    runtime: go1.x
    stage: prod
    region: ap-southeast-2
    memorySize: 128
    timeout: 10
    lambdaHashingVersion: 20201221
    iam:
        role:
            managedPolicies:
                - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

package:
    patterns:
        - '!./**'
        - './bin/**'

functions:
    api:
        handler: bin/main
        environment:
            GIN_MODE: release
        events:
            - http:
                path: /{any+}
                method: ANY
